apiVersion: v2
name: ${{ values.component_id }}
description: Helm chart for ${{ values.component_id }} — managed by RHDH Golden Path
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: ${{ values.owner }}
keywords:
  - ${{ values.language }}
  - ${{ values.system }}
  - golden-path
annotations:
  "backstage.io/component": ${{ values.component_id }}
