apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: ${{ values.system }}
    backstage.io/component: ${{ values.component_id }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ${{ values.system }}
  source:
    repoURL: https://github.com/sansow/${{ values.component_id }}.git
    targetRevision: main
    path: chart/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.target_namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
