apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}-grafana
  namespace: tssc-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/${{ values.repoOwner }}/${{ values.repoName }}.git
    targetRevision: ${{ values.branch }}
    path: ./manifests/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.grafana_namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
